
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578609
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2368D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1847
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1123
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000905
     time (cpu & wall) for ordering          =        0.015625        0.012337
     time (cpu & wall) for other matrix prep =        0.000000        0.002606
     time (cpu & wall) for value input       =        0.000000        0.004501
     time (cpu & wall) for matrix distrib.   =        0.015625        0.016167
     time (cpu & wall) for numeric factor    =        0.031250        0.039474
     computational rate (gflops) for factor  =       19.957791       15.799672

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578761
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2375D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1849
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1124
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002269
     time (cpu & wall) for matrix distrib.   =        0.000000        0.009518
     time (cpu & wall) for numeric factor    =        0.031250        0.022152
     computational rate (gflops) for factor  =       19.960027       28.158148

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578609
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2368D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1848
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1123
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002079
     time (cpu & wall) for matrix distrib.   =        0.000000        0.008582
     time (cpu & wall) for numeric factor    =        0.015625        0.020364
     computational rate (gflops) for factor  =       39.915582       30.626945

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578761
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2375D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1853
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1124
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001961
     time (cpu & wall) for matrix distrib.   =        0.015625        0.008992
     time (cpu & wall) for numeric factor    =        0.015625        0.025645
     computational rate (gflops) for factor  =       39.920055       24.322608
     time (cpu & wall) for numeric solve     =        0.015625        0.002033
     computational rate (gflops) for solve   =        0.566103        4.351314
     effective I/O rate (GB/sec) for solve   =        2.109064       16.211196

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578541
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2366D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1846
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1122
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002376
     time (cpu & wall) for matrix distrib.   =        0.015625        0.008854
     time (cpu & wall) for numeric factor    =        0.015625        0.020644
     computational rate (gflops) for factor  =       39.914438       30.210527

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578350
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2359D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1852
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1120
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002214
     time (cpu & wall) for matrix distrib.   =        0.000000        0.008134
     time (cpu & wall) for numeric factor    =        0.015625        0.024502
     computational rate (gflops) for factor  =       39.909939       25.450274

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578690
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2373D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1851
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1123
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002273
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010349
     time (cpu & wall) for numeric factor    =        0.015625        0.018772
     computational rate (gflops) for factor  =       39.918723       33.225732

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578690
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2373D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8543
     number of negative pivots               =            2140
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1856
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1123
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.002438
     time (cpu & wall) for matrix distrib.   =        0.000000        0.010254
     time (cpu & wall) for numeric factor    =        0.031250        0.027112
     computational rate (gflops) for factor  =       19.959362       23.005343

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =      9

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578761
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2375D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8569
     number of negative pivots               =            2114
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1852
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1124
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002136
     time (cpu & wall) for matrix distrib.   =        0.015625        0.008959
     time (cpu & wall) for numeric factor    =        0.015625        0.023347
     computational rate (gflops) for factor  =       39.920055       26.716760

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =     10

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578761
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2375D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1856
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1124
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001990
     time (cpu & wall) for matrix distrib.   =        0.015625        0.009960
     time (cpu & wall) for numeric factor    =        0.015625        0.021015
     computational rate (gflops) for factor  =       39.920055       29.681080

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578913
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2382D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8545
     number of negative pivots               =            2138
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1857
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1125
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.001925
     time (cpu & wall) for matrix distrib.   =        0.000000        0.008617
     time (cpu & wall) for numeric factor    =        0.031250        0.025769
     computational rate (gflops) for factor  =       19.962273       24.208103

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578761
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2375D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8567
     number of negative pivots               =            2116
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1855
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1124
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002126
     time (cpu & wall) for matrix distrib.   =        0.000000        0.008348
     time (cpu & wall) for numeric factor    =        0.031250        0.022726
     computational rate (gflops) for factor  =       19.960027       27.446937

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =     13

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578691
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2373D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1852
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1123
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002215
     time (cpu & wall) for matrix distrib.   =        0.015625        0.008199
     time (cpu & wall) for numeric factor    =        0.015625        0.020673
     computational rate (gflops) for factor  =       39.918687       30.171213

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =     14

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578761
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2375D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1853
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1124
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002177
     time (cpu & wall) for matrix distrib.   =        0.015625        0.007911
     time (cpu & wall) for numeric factor    =        0.015625        0.026106
     computational rate (gflops) for factor  =       39.920055       23.893099

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =     15

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578761
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2375D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8569
     number of negative pivots               =            2114
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1849
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1124
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001980
     time (cpu & wall) for matrix distrib.   =        0.015625        0.008458
     time (cpu & wall) for numeric factor    =        0.031250        0.032827
     computational rate (gflops) for factor  =       19.960027       19.000922

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =     16

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578761
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2375D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1846
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1124
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.002080
     time (cpu & wall) for matrix distrib.   =        0.000000        0.009788
     time (cpu & wall) for numeric factor    =        0.031250        0.025217
     computational rate (gflops) for factor  =       19.960027       24.734939

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =     17

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578761
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2375D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1844
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1124
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001940
     time (cpu & wall) for matrix distrib.   =        0.000000        0.008237
     time (cpu & wall) for numeric factor    =        0.031250        0.021703
     computational rate (gflops) for factor  =       19.960027       28.740438

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =     18

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578761
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2375D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1849
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1124
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001916
     time (cpu & wall) for matrix distrib.   =        0.000000        0.010057
     time (cpu & wall) for numeric factor    =        0.031250        0.028208
     computational rate (gflops) for factor  =       19.960027       22.112865

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB





  Performance statistics for DSP solver: icalls =     19

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           10683
     no. of nonzeroes in lower triangle of a =          634919
     no. of nonzeroes in the factor l        =         2578761
     ratio of nonzeroes in factor (min/max)  =          0.9730
     number of super nodes                   =             374
     maximum order of a front matrix         =             423
     maximum size of a front matrix          =           89676
     maximum size of a front trapezoid       =           49773
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      6.2375D+08
     no. of floating point ops for solve     =      8.8454D+06
     ratio of flops for factor (min/max)     =          0.9382
     ratio of allocated memory (max/min)     =          1.0331
     number of positive pivots               =            8571
     number of negative pivots               =            2112
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =            1844
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =            1124
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002521
     time (cpu & wall) for matrix distrib.   =        0.000000        0.009527
     time (cpu & wall) for numeric factor    =        0.015625        0.025810
     computational rate (gflops) for factor  =       39.920055       24.167491

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         24732.        0. MB
                95-   1         32768.        0. MB         25185.        0. MB
                95-   2         32768.        0. MB         23908.        0. MB
                95-   3         32768.        0. MB         25629.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB         99454.        1. MB


  Solver Memory allocated on core    0       =       24.944 MB
  Solver Memory allocated on core    1       =       24.354 MB
  Solver Memory allocated on core    2       =       24.759 MB
  Solver Memory allocated on core    3       =       24.143 MB
  Total Solver Memory allocated by all cores =       98.200 MB

