"""
Random Forest Gesture Classifier — 11 Channels
================================================
Script for classifying hand gestures from spike data
generated by Izhikevich neurons (neuromorphic simulation).

Selected dataset: SpikeB_20260610163117_Thalamo1.csv
    -> Thalamo neuron type (blind channel mode)
    -> 11 feature channels:
         ch1..ch5      = spike channels (time-window based)
         dir_x+/y+/z+  = direction spikes when X/Y/Z > 0
         dir_x-/y-/z-  = direction spikes when X/Y/Z < 0
    -> 12th column (total_spike_sum) is ignored.

Data format:
    timestamp, class,
    ch1, ch2, ch3, ch4, ch5,
    dir_x_pos, dir_y_pos, dir_z_pos,
    dir_x_neg, dir_y_neg, dir_z_neg,
    total_spike_sum

Classes (Gestures):
    1 - Open palm
    2 - Fist
    3 - Thumb only
    4 - Pinky only
    5 - Horns (index + ring + thumb)
    6 - Thumb + pinky

Author: Generated with AI assistance
"""

import os
# pyrefly: ignore [missing-import]
import numpy as np
import pandas as pd
import joblib
import matplotlib
matplotlib.use("Agg")  # Non-interactive backend for direct saving
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score,
)
from sklearn.preprocessing import StandardScaler

# ============================================================================
# 1. CONFIGURATION
# ============================================================================

# Path to the chosen dataset (Thalamo — blind channel, 11 channels)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATASET_PATH = os.path.join(
    SCRIPT_DIR,
    "Dataset",
    "blindDir_channel",
    "SpikeBD_20260612175719_Thalamo1.csv",
)

# Column names (11 feature channels + timestamp + class + total)
COLUMN_NAMES = [
    "timestamp",
    "class",
    "spike_channel_1",
    "spike_channel_2",
    "spike_channel_3",
    "spike_channel_4",
    "spike_channel_5",
    "dir_x_pos",
    "dir_y_pos",
    "dir_z_pos",
    "dir_x_neg",
    "dir_y_neg",
    "dir_z_neg",
    "total_spike_sum",
]

# Mapping classes -> gesture names
GESTURE_LABELS = {
    1: "Open palm",
    2: "Fist",
    3: "Thumb only",
    4: "Pinky only",
    5: "Horns (ind+ring+thu)",
    6: "Thumb + pinky",
}

# Model parameters
TEST_SIZE = 0.25
RANDOM_STATE = 42
N_ESTIMATORS = 200
MAX_DEPTH = None  # no depth limit

# ============================================================================
# 2. LOADING AND PREPROCESSING
# ============================================================================

print("=" * 70)
print("  RANDOM FOREST - NEUROMORPHIC GESTURE CLASSIFICATION")
print("=" * 70)

# Loading
print(f"\n[LOAD] Loading dataset: {os.path.basename(DATASET_PATH)}")
df = pd.read_csv(DATASET_PATH, header=None, names=COLUMN_NAMES)

print(f"   Total rows: {len(df)}")
print(f"   Columns: {list(df.columns)}")

# Class info
print("\n[INFO] Class distribution:")
class_counts = df["class"].value_counts().sort_index()
for cls_id, count in class_counts.items():
    label = GESTURE_LABELS.get(cls_id, f"Class {cls_id}")
    print(f"   Class {cls_id} ({label}): {count} samples")

# Remove any rows with missing values
df.dropna(inplace=True)

# Features and target
# We use all 11 channels as features:
#   5 spike channels + 6 direction channels (XYZ pos/neg)
# We DO NOT use the timestamp nor the total sum (redundant)
feature_columns = [
    "spike_channel_1",
    "spike_channel_2",
    "spike_channel_3",
    "spike_channel_4",
    "spike_channel_5",
    "dir_x_pos",
    "dir_y_pos",
    "dir_z_pos",
    "dir_x_neg",
    "dir_y_neg",
    "dir_z_neg",
]

X = df[feature_columns].values
y = df["class"].values

print(f"\n[FEAT] Selected features: {feature_columns}")
print(f"   Shape X: {X.shape}")
print(f"   Shape y: {y.shape}")

# Feature statistics
print("\n[STAT] Feature statistics:")
print(df[feature_columns].describe().round(2).to_string())

# ============================================================================
# 3. TRAIN / TEST SPLIT
# ============================================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    stratify=y,  # maintain class distribution
)

print(f"\n[SPLIT] Train/Test Split (stratified):")
print(f"   Training set: {X_train.shape[0]} samples ({(1 - TEST_SIZE) * 100:.0f}%)")
print(f"   Test set:     {X_test.shape[0]} samples ({TEST_SIZE * 100:.0f}%)")

# Optional normalization (Random Forest doesn't strictly require it, but it helps
# with visualization and data interpretation)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ============================================================================
# 4. RANDOM FOREST MODEL CREATION AND TRAINING
# ============================================================================

print(f"\n[TRAIN] Training Random Forest...")
print(f"   n_estimators: {N_ESTIMATORS}")
print(f"   max_depth: {MAX_DEPTH if MAX_DEPTH else 'No limit'}")
print(f"   random_state: {RANDOM_STATE}")

rf_model = RandomForestClassifier(
    n_estimators=N_ESTIMATORS,
    max_depth=MAX_DEPTH,
    random_state=RANDOM_STATE,
    n_jobs=-1,  # parallelize on all available cores
    class_weight="balanced",  # handle possible class imbalance
)

rf_model.fit(X_train, y_train)
print("   [OK] Model successfully trained!")

# ============================================================================
# 5. MODEL EVALUATION
# ============================================================================

# Predictions
y_pred = rf_model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"\n[RESULT] Accuracy on Test Set: {accuracy * 100:.2f}%")

# Classification report
unique_classes = sorted(df["class"].unique())
target_names = [GESTURE_LABELS[i] for i in unique_classes]
print("\n[REPORT] Classification Report:")
print("-" * 70)
print(
    classification_report(
        y_test,
        y_pred,
        labels=unique_classes,
        target_names=target_names,
    )
)

# Feature importance
print("[KEY] Feature Importance:")
importances = rf_model.feature_importances_
for feat, imp in zip(feature_columns, importances):
    bar = "#" * int(imp * 50)
    print(f"   {feat}: {imp:.4f}  {bar}")

# ============================================================================
# 6. CONFUSION MATRIX - VISUALIZATION
# ============================================================================

# Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=unique_classes)
cm_normalized = confusion_matrix(y_test, y_pred, labels=unique_classes, normalize="true")

# Create figure with 2 subplots: absolute and normalized values
fig, axes = plt.subplots(1, 2, figsize=(18, 7))

# --- Confusion Matrix: Absolute Values ---
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=target_names,
    yticklabels=target_names,
    ax=axes[0],
    linewidths=0.5,
    linecolor="gray",
    cbar_kws={"label": "Count"},
)
axes[0].set_xlabel("Predicted", fontsize=12, fontweight="bold")
axes[0].set_ylabel("True", fontsize=12, fontweight="bold")
axes[0].set_title("Confusion Matrix (Absolute Values)", fontsize=14, fontweight="bold")
axes[0].tick_params(axis="x", rotation=30)
axes[0].tick_params(axis="y", rotation=0)

# --- Confusion Matrix: Normalized ---
sns.heatmap(
    cm_normalized,
    annot=True,
    fmt=".2f",
    cmap="Greens",
    xticklabels=target_names,
    yticklabels=target_names,
    ax=axes[1],
    linewidths=0.5,
    linecolor="gray",
    vmin=0,
    vmax=1,
    cbar_kws={"label": "Proportion"},
)
axes[1].set_xlabel("Predicted", fontsize=12, fontweight="bold")
axes[1].set_ylabel("True", fontsize=12, fontweight="bold")
axes[1].set_title(
    "Confusion Matrix (Row-Normalized)", fontsize=14, fontweight="bold"
)
axes[1].tick_params(axis="x", rotation=30)
axes[1].tick_params(axis="y", rotation=0)

# Main title
fig.suptitle(
    f"Random Forest - Neuromorphic Gesture Classification\n"
    f"Dataset: Thalamo1 | Accuracy: {accuracy * 100:.2f}% | "
    f"Estimators: {N_ESTIMATORS}",
    fontsize=15,
    fontweight="bold",
    y=1.02,
)

plt.tight_layout()

# Save
output_path = os.path.join(SCRIPT_DIR, "output", "confusion_matrix_thalamo_11ch.png")
os.makedirs(os.path.dirname(output_path), exist_ok=True)
fig.savefig(output_path, dpi=150, bbox_inches="tight")
print(f"\n[SAVE] Confusion Matrix saved to: {output_path}")
plt.close(fig)

# ============================================================================
# 7. FEATURE IMPORTANCE - VISUALIZATION
# ============================================================================

fig2, ax2 = plt.subplots(figsize=(12, 7))

colors = sns.color_palette("viridis", len(feature_columns))
bars = ax2.barh(feature_columns, importances, color=colors, edgecolor="black")
ax2.set_xlabel("Importance", fontsize=12, fontweight="bold")
ax2.set_title(
    "Feature Importance - Random Forest\n(Neuromorphic Spike Channels)",
    fontsize=14,
    fontweight="bold",
)
ax2.invert_yaxis()

# Add values on bars
for bar, imp in zip(bars, importances):
    ax2.text(
        bar.get_width() + 0.005,
        bar.get_y() + bar.get_height() / 2,
        f"{imp:.4f}",
        va="center",
        fontsize=10,
    )

plt.tight_layout()

output_path_fi = os.path.join(SCRIPT_DIR, "output", "feature_importance_thalamo_11ch.png")
fig2.savefig(output_path_fi, dpi=150, bbox_inches="tight")
print(f"[SAVE] Feature Importance saved to: {output_path_fi}")
plt.close(fig2)

# ============================================================================
# 8. MODEL EXPORT (for LabVIEW Python Node integration)
# ============================================================================

model_output_path = os.path.join(SCRIPT_DIR, "output", "rf_model_thalamo_11ch.pkl")
joblib.dump(rf_model, model_output_path)
print(f"\n[SAVE] Trained model saved to: {model_output_path}")

print("\n" + "=" * 70)
print("  [OK] ANALYSIS SUCCESSFULLY COMPLETED")
print("=" * 70)
